import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { createTheme, MantineProvider } from "@mantine/core";
import { theme } from "./style/theme";
import {QueryClientProvider} from "@tanstack/react-query"
import queryClient from "./validation/Client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
   
    <html lang="en">
       
      <body className={inter.className}>  <QueryClientProvider client={queryClient} > <MantineProvider theme={theme}>{children}</MantineProvider></QueryClientProvider> </body>

    </html>
 
  );
}
